version: '3.6'
services:
  postgres:
    env_file:
      - .env
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  graphql-engine:
    env_file:
      - .env
    image: hasura/graphql-engine:v1.2.0-beta.3
    ports:
    - "8600:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
volumes:
  db_data:

